// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {protodef} from '../models';
import {main} from '../models';
import {net} from '../models';

export function GetGameMap():Promise<protodef.UserPositionedGameMap>;

export function GetId():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function LogIn(arg1:string):Promise<number>;

export function SendStatus(arg1:main.ClientStatus):Promise<void>;

export function SetConn(arg1:net.UDPConn):Promise<void>;

export function SetGameMap(arg1:protodef.UserPositionedGameMap):Promise<void>;

export function SetId(arg1:string):Promise<void>;

export function SetServerPort(arg1:number):Promise<void>;

export function StartUpdateMapStatus():Promise<void>;
