// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetId() {
  return window['go']['main']['App']['GetId']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function LogIn(arg1) {
  return window['go']['main']['App']['LogIn'](arg1);
}

export function SendStatus(arg1) {
  return window['go']['main']['App']['SendStatus'](arg1);
}

export function SetId(arg1) {
  return window['go']['main']['App']['SetId'](arg1);
}

export function StartUpdateMapStatus() {
  return window['go']['main']['App']['StartUpdateMapStatus']();
}
